<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ8HW6R8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ8HW6R8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ8HW6R8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ8HW6R8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ8HW6R8\App_KernelDevDebugContainer([
    'container.build_hash' => 'J8HW6R8',
    'container.build_id' => '82e4d864',
    'container.build_time' => 1610966863,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ8HW6R8');
