<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSf35fOe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSf35fOe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSf35fOe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSf35fOe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSf35fOe\App_KernelDevDebugContainer([
    'container.build_hash' => 'Sf35fOe',
    'container.build_id' => '0b9cbe75',
    'container.build_time' => 1611071891,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSf35fOe');
