<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJatY37k\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJatY37k/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJatY37k.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJatY37k\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJatY37k\App_KernelDevDebugContainer([
    'container.build_hash' => 'JatY37k',
    'container.build_id' => '61cd3281',
    'container.build_time' => 1610703928,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJatY37k');
